### ISSUE TITLE
Export all types used as function params on index

### ISSUE THREAD

**Issue by QuentinFrc** [resend/resend-node#122]
Could be developer friendly to export type directly form index to able to do this import

`import { Resend, CreateEmailOptions } from 'resend';`

rather than this one

`import { CreateEmailOptions } from 'resend/build/src/emails/interfaces';`

My use case of needing thoses types is not really interesting but I think other peoples would make a great things with that

**Comment by ghosh** [comment]
This no longer works in `2.1.0`, seems like the package build was changed in #259

**Comment by iBobik** [comment]
Just wanted to use the type, but cannot
<img width="833" alt="Bez názvu" src="https://github.com/resend/resend-node/assets/614232/7ea9b03c-e03d-449f-aba8-b313ec7fe290">
