### ISSUE TITLE
React.FC returns ReactNode since 18.2

### ISSUE THREAD

**Issue by Christian-Schoenlein** [resend/resend-node#124]
Upgraded to the latest version of `@types/react` and a `FunctionalComponent` no longer returns a `ReactElement` which resend expects, instead a `ReactNode` is returned

From the `@types/react` codebase:
## Version 18.0.28
```ts
interface FunctionComponent<P = {}> {
    (props: P, context?: any): ReactElement<any, any> | null;
    propTypes?: WeakValidationMap<P> | undefined;
    contextTypes?: ValidationMap<any> | undefined;
    defaultProps?: Partial<P> | undefined;
    displayName?: string | undefined;
}
```

## Version 18.2.14
```ts
interface FunctionComponent<P = {}> {
    (props: P, context?: any): ReactNode;
    propTypes?: WeakValidationMap<P> | undefined;
    contextTypes?: ValidationMap<any> | undefined;
    defaultProps?: Partial<P> | undefined;
    displayName?: string | undefined;
}
```

**Comment by bukinoshita** [comment]
Any ideas?

**Comment by jayanratna** [comment]
I tried updating the type on the SDK but the underlying react-email render function doesnt accept the new type. It would need to be updated there too.

I would say the new type is a better option.

**Comment by chukwumaokere** [comment]
I had some weird errors pop up that describe whats written here, so what I did was just take out the React.FC type designation and turned it into a regular JSX element.
It renders the same, the email that gets sent is correct still, so ended up redeclaring my component pretty much exactly like this: 

But i was just wondering why this popped up all of a sudden

> I'm not sure why this type change was introduced, and I couldn't find any information about what exact version this happened in.
> 
> Since ReactNode is a union type including ReactElement, most use cases will still work, but through a type error. A quick fix would be to wrap it in a fragment to make sure it is a ReactElement and not a boolean that was passed.
> 
> ```ts
> type ReactNode =
>     | ReactElement
>     | string
>     | number
>     | Iterable<ReactNode>
>     | ReactPortal
>     | boolean
>     | null
>     | undefined
>     | DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_REACT_NODES[keyof DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_REACT_NODES];
> ```
> 
> A cleaner way would be to remove the FC type from the email component and let the type be inferred as a JSX.Element that extends ReactElement.
> 
> ## Before
> ```tsx
> import { type FC } from "react";
> 
> interface EmailTemplateProps {
>   firstName: string;
> }
> 
> export const EmailTemplate: FC<Readonly<EmailTemplateProps>> = ({
>   firstName,
> }) => (
>   <div>
>     <h1>Hey, {firstName}!</h1>
>   </div>
> );
> ```
> 
> ## After
> ```tsx
> interface EmailTemplateProps {
>   firstName: string;
> }
> 
> export const EmailTemplate = ({ firstName }: EmailTemplateProps) => (
>   <div>
>     <h1>Hey, {firstName}!</h1>
>   </div>
> );
> ```

**Comment by vcapretz** [comment]
does the errors still occur? I actually just opened a PR #401 that should improve our typing even further

feel free to reopen the issue if it's still happening in latest Resend SDK + latest React versions 🙏
