### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by QuentinFrc** [resend/resend-node#138]
Is a call to `https://api.resend.com/` a health check and if it is, can this fetch request have a dedicated method in the Resend class. 
It could make easy to create a status check for email service.

**Comment by vcapretz** [comment]
hey there, a call to our base path is not necessarily a base path and it will not necessarily respond with specific fields if say only part of the endpoints are down for some reason.

I would say that a more accurate and reliable way for you to understand the status of our systems is to subscribe to https://resend-status.com/, where we post incident statuses as they happen. 

in the latest versions of the SDK we are now throwing an error if we can't reach the API:
```
{
  name: 'application_error',
  message: 'Unable to fetch data. The request could not be resolved.',
}
```
so feel free to check for this specific case if you need to in your code 🙏 

thanks!

**Comment by bcheidemann** [comment]
@vcapretz not sure if this was what @QuentinFrc was asking about, but I'd like to include Resend in our applications deep health check. This health check is not to validate that resend services are operational, it's to ensure that new deployments are configured and working correctly. For example, it checks that we can communicate with the DB, NATS client, etc. But there appears to be no way idiomatic way to check this with the Resend client. Something as simple as the following would be useful.

```
const resend = new Resend("...");

await resend.authenticate();
// or...
await resend.ping();
```

This helps guard against application configuration errors (e.g. incorrect API key), network configuration errors (e.g. new deployment may not allow outbound traffic to the resend API), etc.
