### ISSUE TITLE
Typescript issue with version `0.17.2` on the `react` field 

### ISSUE THREAD

**Issue by MatteoGauthier** [resend/resend-node#154]
Hey Resend Team, I got a TS issue after upgrading resend to `0.17.2` with typescript `5.1.6`

```
Argument of type '{ from: string; to: string | string[]; subject: string; react: ReactElement<any, string | JSXElementConstructor<any>> | ReactNode; }' is not assignable to parameter of type 'CreateEmailOptions'.
  Type '{ from: string; to: string | string[]; subject: string; react: ReactElement<any, string | JSXElementConstructor<any>> | ReactNode; }' is not assignable to type 'Required<Pick<CreateEmailBaseOptions, "text">> & Partial<Pick<CreateEmailBaseOptions, "react" | "html">> & { ...; }'.
    Property 'text' is missing in type '{ from: string; to: string | string[]; subject: string; react: ReactElement<any, string | JSXElementConstructor<any>> | ReactNode; }' but required in type 'Required<Pick<CreateEmailBaseOptions, "text">>'.ts(2345)
create-email-options.interface.d.ts(13, 5): 'text' is declared here.
```

<img width="818" alt="image" src="https://github.com/resendlabs/resend-node/assets/32040951/46cc6ce5-1161-420c-8166-84f4ccb379ec">

**Comment by bukinoshita** [comment]
Can you upgrade Typescript?

**Comment by MatteoGauthier** [comment]
> Can you upgrade Typescript?

On the screenshot, I'm on 5.1.6 (which is the current latest) and I tried with the 5.2.0-beta and I still got the issue

**Comment by estubmo** [comment]
Can confirm, getting the same error. If I cast the react element to JSX.Element the error goes away, but I'd rather if React.ReactNode worked as it's described in the CreateEmailBaseOptions interface.

**Comment by benjaminwaterlot** [comment]
The cleanest workaround right now is indeed:

```
          react: EmailTemplate({
            link: props.url,
          }) as React.ReactElement,
```

I guess the `RequireAtLeastOne` type-fest type doesn't work well with ReactNode (maybe because it can be `null`).

```
export type CreateEmailOptions = RequireAtLeastOne<CreateEmailBaseOptions, 'react' | 'html' | 'text'>;
```

**Comment by gregegan** [comment]
> The cleanest workaround right now is indeed:
> 
> ```
>           react: EmailTemplate({
>             link: props.url,
>           }) as React.ReactElement,
> ```
> 
> I guess the `RequireAtLeastOne` type-fest type doesn't work well with ReactNode (maybe because it can be `null`).
> 
> ```
> export type CreateEmailOptions = RequireAtLeastOne<CreateEmailBaseOptions, 'react' | 'html' | 'text'>;
> ```

Can confirm this fixes the issue

**Comment by bukinoshita** [comment]
We remove type-fest

**Comment by softmarshmallow** [comment]
This issue is still present with

```
"resend": "^3.1.0",
"typescript": "^5.3.3"
```

Simply following the nextjs quickstart - https://resend.com/docs/send-with-nextjs#3-send-email-using-react


<img width="627" alt="Screenshot 2024-02-04 at 3 06 04 PM" src="https://github.com/resend/resend-node/assets/16307013/b531eae6-1519-48a1-abbf-e37cad2b0e1d">

**Comment by JamesSingleton** [comment]
@bukinoshita I am still running into this as well

```json
"resend": "^3.1.0",
"typescript": "^5.3.3"
```

This is just from following the [example for Next.js](https://resend.com/docs/send-with-nextjs)

![Screenshot 2024-02-10 at 10 51 33 AM](https://github.com/resend/resend-node/assets/21000200/0d61ba0c-7fbe-473c-90d8-7912c8db3609)
