### ISSUE TITLE
ICS Calendar attachments are not recognized by outlook

### ISSUE THREAD

**Issue by tscans** [resend/resend-node#198]
I've tried attaching an ICS Calendar invite. The attachment itself works and is sent to the email. Gmail appears to recognize the ICS file and adds it to the user calendar. Outlook does not recognize it. Using the same domain and same configurations, this will work fine using SendGrid. The only real difference I could see was SendGrid asks for a `type` key like `type: 'text/calendar; method=REQUEST'` to make this work with Outlook.

**Comment by brianjuhl** [comment]
Were you able to get this working or did you migrate to a different service?

**Comment by tscans** [comment]
> Were you able to get this working or did you migrate to a different service?

Sadly still using SendGrid. It's a shame because Id love to use resend.

**Comment by vcapretz** [comment]
answered in the examples repo as well: https://github.com/resend/resend-examples/issues/154#issuecomment-2204267914 

in the latest version of our SDK (v3.4.0 as of now), the `attachments` array accepts a `content_type` param 🙏

**Comment by tscans** [comment]
@vcapretz  unfortunately this fix for Outlook now produces the same problem on Gmail. The iCal renders in Outlook but Gmail will not recognize it and instead simply allows the ics to be downloaded as an attachment. Any ideas? I would imagine sending calendar invites via email would be popular with Resend.

**Comment by jfade** [comment]
@tscans I'm running into the same issue suddenly. Gmail no longer recognizes ICS calendar files that it previously did, providing the visual integration directly in the inbox with the Yes No Maybe. It has worked for years and suddenly doesn't. I strongly suspect Google changed something in how they process these things. I read somewhere they're wanting to push people towards registering and using this Schema format instead: https://developers.google.com/gmail/markup/reference/event-reservation#json-ld

But it seems crazy to me that they'd suddenly drop support for what is pretty standard stuff being used by a LOT of applications...

**Comment by aalmho** [comment]
Experiencing the problem of the ics not being recognised by Outlook, but works fine on Gmail. Does anyone know the current state of this problem? 

@vcapretz I see the change of yours content_type as snake case was changed to camel case. Is the what is causing Outlook to not recognise it?
