### ISSUE TITLE
Pass in dynamic prop to "react" based on "to" email

### ISSUE THREAD

**Issue by JamesSingleton** [resend/resend-node#229]
This isn't really an _issue_ but discussions aren't enable, so here I am. I am in a situation where I want to send emails to a group of people, lets say 10-20 email addresses. However, I would like to customize it with "Dear John Doe" or "Dear Jane Doe", you get the point. However, I don't know of a way other than to create an `await resend.emails.send({})` for each email address. Is there a way that I could possibly _avoid_ that or what's the best practice around that?

**Comment by bukinoshita** [comment]
If you're using the `react` key, you can pass the email component like this

```
"react": MyEmail({ name: "James" })
```

**Comment by JamesSingleton** [comment]
> If you're using the `react` key, you can pass the email component like this
> 
> ```
> "react": MyEmail({ name: "James" })
> ```

But that name will be different between the let’s say 10-20 emails I’m sending the email to.

**Comment by bukinoshita** [comment]
Can you share the code you're currently using? I'm assuming that you have a loop in a contacts array

**Comment by JamesSingleton** [comment]
So this is what my `/app/api/send/route.ts` looks like

```ts
import { NextResponse } from 'next/server'
import { Resend } from 'resend'

import EmailTemplate from '@/emails/emailTemplate'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: Request) {
  const { name, email, message, subject } = await request.json()

  try {
    const data = await resend.emails.send({
      from: `Email From <${process.env.EMAIL_FROM_ADDRESS}>`,
      to: [
        'email1@example.com',
        'email2@example.com',
        'email3@example.com',
        'email4@example.com'
      ],
      reply_to: email,
      subject: subject,
      react: EmailTemplate({ name, email, subject, message }),
    })

    return NextResponse.json(data)
  } catch (error) {
    return NextResponse.json({ error })
  }
}
```

Which is the basic example provided in the README.

**Comment by JamesSingleton** [comment]
@bukinoshita any ideas here?

**Comment by paulhmorris** [comment]
@JamesSingleton It wouldn't make sense that you could send a single email to multiple people, with that email having different content for each recipient.

The appropriate way to handle this would be to map your contacts into an array of emails, then use the [batch](https://resend.com/docs/api-reference/emails/send-batch-emails) function to send one those out.

Cheers!

**Comment by JamesSingleton** [comment]
Ah! I didn’t know about the batch functionality! Thanks for pointing that out!
