### ISSUE TITLE
Email requests using unverified email address in `from` field are not thrown

### ISSUE THREAD

**Issue by OussamaFadlaoui** [resend/resend-node#275]
### Subject of the issue
I used the Node SDK package `resend` to send my first email. Upon using an unverified domain in the `from` field, my request seemed to go OK (promise was not rejected). When I went to the dashboard, I discovered the request was rejected with status code 403:
<img width="1058" alt="image" src="https://github.com/resendlabs/resend-node/assets/59295517/e0697f1f-fca7-4eec-87a4-5f4b3ba96d8e">
That's a valid point, however, why did the Promise not throw an appropriate error?

### Steps to reproduce
1. Create Resend account
2. Install `resend` NPM package
3. Send an email in Node.js using an unverified domain name in the `from` field

### Expected behaviour
The promise should be rejected on 403 status codes..

### Actual behaviour
No errors being thrown.

**Comment by bukinoshita** [comment]
Hey @OussamaFadlaoui, would you mind sharing the request you're sending?

**Comment by everybodyloveshaggis** [comment]
@bukinoshita - an example I can give to back up @OussamaFadlaoui 's example is this

```
let data;
    try {
        data = await resend.emails.send({
            from: 'onboarding@resend.com',     //this is wrong on purpose to throw an error
            to: 'BLANKED_OUT_FOR_QUESTION_RESPONSE@gmail.com',
            subject: 'Message from cv-site-nextjs',
            reply_to: senderEmail as string,
            react: React.createElement(ContactFormEmail,
                {
                    senderMessage: senderMessage as string,
                    senderEmail: senderEmail as string
                }),
        });
        //interrogation required to check for error
        if(data.error?.message !== null)
            {
                throw data.error;
            }
    } catch (error: unknown) {
        return {
            error: getErrorMessage(error),
        };
    }
```

You'll see I have had to interrogate the data object to pull out the child error object with the below
```
 if(data.error?.message !== null)
  {
      throw data.error;
  }
```
as I do not hit the catch block even though the following error is displayed on the UI
![image](https://github.com/resend/resend-node/assets/111693925/93935af0-f923-4143-be7c-b505d6f885e8)

**Comment by vcapretz** [comment]
hey there, in the latest versions of the SDK basically all methods should always return correctly and not throw any errors, we do that so in your codebase you don't have to wrap our code in a `try/catch` method.

if the requests fail for any reason, our SDK will return a populated `error` object with some description of what happened.

using the example for an unverified domain the `error` object will be like:
```
{
  statusCode: 403,
  message: 'The test.com domain is not verified. Please, add and verify your domain on https://resend.com/domains',
  name: 'validation_error'
}
```

please let us know if the issue still persists and feel free to reopen it in here 🙏

**Comment by OussamaFadlaoui** [comment]
> hey there, in the latest versions of the SDK basically all methods should always return correctly and not throw any errors, we do that so in your codebase you don't have to wrap our code in a `try/catch` method.
> 
> if the requests fail for any reason, our SDK will return a populated `error` object with some description of what happened.
> 
> using the example for an unverified domain the `error` object will be like:
> ```
> {
>   statusCode: 403,
>   message: 'The test.com domain is not verified. Please, add and verify your domain on https://resend.com/domains',
>   name: 'validation_error'
> }
> ```
> 
> please let us know if the issue still persists and feel free to reopen it in here 🙏 

Obviously this is not my library, but I still want to say that having tries and catches all over code does not take away from the quality of a library. In fact, it is the proper way of handling errors. After all, this library is performing a promise, and promises are expected to either resolve or reject

Therefore I find the reasons for this design decision to be a bit odd and steering away from the traditional way of using promises in third party libraries.
