### ISSUE TITLE
Corrupted attachments in resend emails

### ISSUE THREAD

**Issue by amunim** [resend/resend-node#277]
I have a data uri from the front-end, that is sent via resend on my next.js back-end, but when I give the content as this string, the image is corrupted.
![image](https://github.com/resendlabs/resend-node/assets/24316328/d91969f1-da7d-4859-ae9a-8adc736c2f9e)

    const data = await resend.emails.send({
        from: 'AMunim <onboarding@resend.dev>',
        to: ['text@gmail.com'],
        subject: 'Test Receipt for local dev',
        text: "Thank you for your order",
        attachments: [{
            content: req.body?.pdf, //data uri image png here
            filename: 'receipt.png'
        }]
    });

I've also tried creating pdf but it either doesn't send the email or corrupted file.

    const pdf = new jsPDF();
    pdf.addImage(req.body?.pdf, 'PNG', 0, 0);

    const data = await resend.emails.send({
        from: 'AMunim <onboarding@resend.dev>',
        to: ['abdulmunim2005@gmail.com'],
        subject: 'Test Receipt for local dev',
        text: "Thank you for your order",
        attachments: [{
            content: pdf.output(),
            filename: 'receipt.png'
        }]
    });

How can I get around this bug? because when I inspect the data uri and use it on my browser the image is fine

**Comment by bukinoshita** [comment]
What's the type of your attachment?

**Comment by amunim** [comment]
My type was pdf and png. If anybody else stumbles upon this, this is how I solved the issue. 
```javascript
const pdfOut = pdf.output("datauristring");
//later
attachments: [{
                content: pdfOut.substring(pdfOut.indexOf(",")),
                encoding: "base64",
                contentType: "application/pdf",
                filename: 'receipt.pdf'
            }]
```

Basically we chop the part of data:application/pdf, and include only the base64 string, for some reason it doesn't do it automatically also using the data uri in `path` also didn't work as shown in examples.

**Comment by bukinoshita** [comment]
Here's an example of sending the data string as base64 https://github.com/resend/resend-examples/pull/69/commits/c7ddac7e2f102ad9e3ca1fee5a78425e25018029#diff-b8e79580b59a11c05635949a07513d4d2ec12779350f9589063f0a981a355238

**Comment by AdsonCicilioti** [comment]
@bukinoshita , Resend no longer accepts Buffer files via formData payload?
