### ISSUE TITLE
Can not override Content-Type headers for ics

### ISSUE THREAD

**Issue by eam-k** [resend/resend-node#278]
## Context
- I am sending a ics file
- I set the headers like this:
```console
 "headers": {
        "Content-Type": "text/calendar; charset=utf-8; method=REQUEST; name=invite.ics"
    },
````
- The file is a string that I pass as:
```console
   "attachments": [{
        "content": "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nCALSCALE:GREGORIAN...more details about invite",
        "filename": "invite.ics"
    }]
```

- In Resend platform I am getting this error:
```console
{
    "name": "application_error",
    "message": "Duplicate header 'Content-Type'.",
    "statusCode": 500
}
```

## What should be expected?

Since I am the developer, I want to have freedom to set the headers. One of the reasons is to make sure the content is correctly interpreted when the attachment is sent. For example, when I see the attachment I can see that it is correctly sent as attachment but the content inside the file is not correct probably a buffer/unrecognizable characters, this confuses gmail and mark it as a potential risk, what I would expect from a library and the platform is:
- Able to see the exact headers used
- Override the headers 

## Notes
Hey devs, I just found out that using Buffer with uft-8 encoder did the trick:
```console
{
  content: Buffer.from(iCalInvitation, 'utf-8'),
  filename: 'invite.ics',
},
```
I was trying to follow a mix between two examples, where the ics file was sent as a string (attachment).
https://github.com/resend/resend-examples/blob/main/with-ical/src/pages/api/send.ts
 
Turns out that sending a string is not enough, somehow the content is not interpreted correctly. 

I also had some inconsistencies with my ics file so I decided to create a valid one from another platform, one that can be added to calendar and also to discard other factors in this issue , after getting a valid ics I tried to send it different ways, so Buffer was how I was able to send it without issues. 

I will let this issue open so you guys can close it, if you close it I will assume you read this issue.

```console
Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.
Antoine de Saint-Exupéry
```

**Comment by johanneskares** [comment]
same issue here

**Comment by vcapretz** [comment]
hey there, we have actually fixed this issue by allowing developers to pass a custom header specifically to the `attachment` in question when using `.ics` files. you can find an example here: https://github.com/resend/resend-examples/blob/main/with-ical/src/pages/api/send.ts#L39 

so basically if you need to customize any header for iCal events you now should be able to 🙏
