### ISSUE TITLE
Crashes on Cloudflare Workers, because process is not defined

### ISSUE THREAD

**Issue by bndkt** [resend/resend-node#279]
I'm trying to use the SDK in Remix running on Cloudflare Workers, but it crashes with

```
service core:user:worker: Uncaught ReferenceError: process is not defined
```

This is due to the lines https://github.com/resend/resend-node/blob/68ada752b7fb34f1fb29b1501a87b7fa643d16d9/src/resend.ts#L12-L13 and https://github.com/resend/resend-node/blob/68ada752b7fb34f1fb29b1501a87b7fa643d16d9/src/resend.ts#L27 referencing `process.env.RESEND_BASE_URL`, `process.env.RESEND_USER_AGENT`, and `process.env.RESEND_API_KEY`.

If those lines were written more defensively like this:

```
if (typeof process !== 'undefined' && process.env.YOUR_ENV_VARIABLE) {
  // Use process.env.YOUR_ENV_VARIABLE safely
} else {
  // Handle the case when the variable is not available
}
```

it would work on Cloudflare as well, given that the use of environment variables in these places is optional. Would you be interested in me sending a PR to make it compatible with Cloudflare Workers?

**Comment by someguy9** [comment]
Would love to be able to use workers, having the same issue here

**Comment by bukinoshita** [comment]
Closing in favor of https://github.com/resend/resend-node/issues/237

**Comment by bukinoshita** [comment]
We do have this open PR, but couldn't test it yet, I don't think it will fix it

https://github.com/resend/resend-node/pull/274
