### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by Scerutti** [resend/resend-node#288]
# Issue with Resend Service during Backend Deployment

I am deploying a backend, and at the moment of using the Resend service, I encounter the following error:

<img width="700" alt="image" src="https://github.com/resend/resend-node/assets/93475201/bf1a3d3f-6ae5-4568-81d9-f7227b5e4579">

## Error Description

I am deploying a backend, and at the moment of using the Resend service I get the error shown in the image below. What is the reason?

## Request for Assistance

I would appreciate any assistance or insights into the potential causes and solutions for this issue. If anyone has encountered a similar problem or has suggestions on how to resolve it, please share your expertise. Thank you!

**Comment by ZeeshanZulfiqarAli** [comment]
I had the same problem and got it resolved by using the latest version of node.

**Comment by Scerutti** [comment]
That was indeed the solution. Thank you very much for your help @ZeeshanZulfiqarAli
