### ISSUE TITLE
"Headers is not defined" error message when setting up the API key

### ISSUE THREAD

**Issue by nahuelleiva** [resend/resend-node#290]
Hi, I noticed that when setting up the API key in my code, my Node.JS server just exits with this error message:
![image](https://github.com/resend/resend-node/assets/35842291/781ac2dd-7883-49b9-9048-fd7386af86a7)

The same thing happens if I set the secret key inside a local function, I get the same error message in return. Any suggestions?

**Comment by asadiqbal791** [comment]
The identified issue was successfully resolved by upgrading the Node.js version from 16.13.1 to 18.12.0 on my side.
