### ISSUE TITLE
Can't Update a Contact's Email

### ISSUE THREAD

**Issue by theotarr** [resend/resend-node#308]
I'm trying to update the `email` field of a contact, but it isn't in the `UpdateContactOptions` [(link to code)](https://github.com/resend/resend-node/blob/838d483db14cc6ee7effda98225f7695eb0aab62/src/contacts/interfaces/update-contact.interface.ts#L4) interface.

The [docs](https://resend.com/docs/api-reference/contacts/update-contact#body-parameters) include an `email` in the body for this request but providing the `email` field when updating contacts shows a type error:
```
await resend.contacts.update({
        id: contactId,
        email: payload.email || undefined,
        firstName: payload.name || undefined,
      })
```

It looks like this isn't just a type error, it also isn't sent in the [body of the patch request](https://github.com/resend/resend-node/blob/838d483db14cc6ee7effda98225f7695eb0aab62/src/contacts/contacts.ts#L63).

**Comment by bukinoshita** [comment]
Can you upgrade to the latest?
