### ISSUE TITLE
Resend dependency broke Jest

### ISSUE THREAD

**Issue by DawChihLiou** [resend/resend-node#310]
`@react-email/render` uses `pretty` that has a common js dependency. It breaks Jest. It'd be great to know how to fix it. Thanks.

<img width="1025" alt="Screenshot 2024-01-22 at 12 23 45" src="https://github.com/resend/resend-node/assets/4335023/46e2094a-193a-4dc1-b4b5-1137ef7a29bd">

**Comment by bukinoshita** [comment]
@DawChihLiou Do you have a minimal reproducible repository for us to test?
