### ISSUE TITLE
[bug?]: contacts API not working

### ISSUE THREAD

**Issue by caseybaggz** [resend/resend-node#332]
Hello!

So far I've been able to send emails via the `resend.emails.send` method which works great, but using the `resend.contacts.create` method doesn't seem to work at all? On the free plan test driving the value but I'm not seeing anywhere that this should be an issue?

Just double checking in case it's me? Thanks!

Code:
```javascript
const { error: audienceError } = await resend.contacts.create({
      email,
      audienceId: "<General-audience-id>",
    });
```

**Comment by pruthivithejan** [comment]
I have the same issue, Trying to add a newsletter form to my website and it errors out like this 

`Error {
    stack: 'Error: Failed to fetch\n' +
      '    at http://localhost:4321/src/components/Newsletter.tsx?t=1709032440876:43:21',
    message: 'Failed to fetch'
  }`

**Comment by caseybaggz** [comment]
This was a user error. I fixed it by changing my API key to use "full access". Closing.
