### ISSUE TITLE
auto reply

### ISSUE THREAD

**Issue by maxkarkowski** [resend/resend-node#336]
Hi,

i am thinking to use resend for a contact form in my next project. When submitting the form the admin should get an email with the inquriy but also the user should automatically get an auto reply. is that possible?

**Comment by sourabpramanik** [comment]
In your submission call where you are sending an email to the admin, the same way you can capture the user's email and send a response email back.

**Comment by vcapretz** [comment]
hey @maxkarkowski, from what I understand you can either send an email to both of them, or you can also the `reply_to` field, where you can specify a different email from the sender so when the user hits reply the correct one receives it! 

closing the issue for now but feel free to reopen if you have any questions still
