### ISSUE TITLE
Batch emails with attachments are not showing up

### ISSUE THREAD

**Issue by devwithjsantos** [resend/resend-node#409]
I tried both batching and sending one at a time email using the following methods:

- `resend.batch.send` 
- `resend.emails.send`

And it looks like the actual attachment isn't sent when using the batch send. But with the `resend.emails.send` I can receive the attachment.

**Comment by bukinoshita** [comment]
@devwithjsantos Attachments is not supported in the batch endpoint yet. We are still working on add support, you can check the limitation in the [docs](https://resend.com/docs/api-reference/emails/send-batch-emails#limitations)

**Comment by Cayllen** [comment]
Also voicing support for this one

**Comment by JuampiCarosi** [comment]
+1. This feature would be really helpful, I currently have to make a batch of 10 requests and sleep 1 second between each batch beacuse i need to send +100 mails all at once with attachments.

**Comment by alexblazevski** [comment]
+1 as well - would be a really helpful feature for us

**Comment by Onyelaudochukwuka** [comment]
+1 as well, just finished with the implementation, only to see it not working with attachments.
